export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const CHANGE_SCHEDULE_VIEW = 'APP/CHANGE_SCHEDULE_VIEW';
export const LOADED_SCHEDULE = 'EVENTS/LOADED_SCHEDULE';
export const SHOW_FORM_CREATION_EVENT = 'APP/SHOW_FORM_CREATION_EVENT';
export const HIDE_FORM_CREATION_EVENT = 'APP/HIDE_FORM_CREATION_EVENT';
